#!/usr/bin/python3
import sys
import time

def factorize(num):
    factors = []
    for i in range(2, num):
        if num % i == 0:
            factors.append((i, num // i))
            break
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        return

    file_name = sys.argv[1]

    try:
        with open(file_name, 'r') as file:
            numbers = file.readlines()
            for number in numbers:
                num = int(number.strip())
                factors = factorize(num)
                print(f"{num}={factors[0][0]}*{factors[0][1]}")
    except FileNotFoundError:
        print(f"File {file_name} not found.")

if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
