#!/usr/bin/python3
import sys
import time

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def pollard_rho(n):
    if n == 1:
        return [1]
    if n % 2 == 0:
        return [2, n // 2]

    x = 2
    y = 2
    d = 1

    f = lambda x: (x ** 2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)

    if d == n:
        return None
    else:
        return [d, n // d]

def main():
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        return

    file_name = sys.argv[1]

    try:
        with open(file_name, 'r') as file:
            number = int(file.readline().strip())
            factors = pollard_rho(number)
            if factors:
                print(f"{number}={factors[1]}*{factors[0]}")
            else:
                print(f"No prime factors found for {number}.")
    except FileNotFoundError:
        print(f"File {file_name} not found.")

if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
